/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.eje2_IO;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        int x, y, suma, resta, multiplicacion;
        float division;
        Scanner myScanner;

        myScanner = new Scanner(System.in);

        System.out.print("Introduce un valor a X: ");
        x = myScanner.nextInt();
        System.out.print("Introduce un valor a Y: ");
        y = myScanner.nextInt();

        suma = x + y;
        resta = x - y;
        multiplicacion = x * y;
        division = Float.intBitsToFloat(x) / Float.intBitsToFloat(y);

        System.out.println("X = "
                + x
                + "\nY = "
                + y
                + "\nSuma = "
                + suma
                + "\nResta = "
                + resta
                + "\nMultiplicación = "
                + multiplicacion
                + "\nDivisión = "
                + division
                + "\n");

    }
}
