/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.eje2_conditions;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        int num;
        Scanner myScanner = new Scanner(System.in);

        System.out.println("Escribe un número del 1 al 7: ");
        num = myScanner.nextInt();

        switch (num) {
            case 1:
                System.out.println("Lunes");
                break;
            case 2:
                System.out.println("Martes");
                break;
            case 3:
                System.out.println("Miercoles");
                break;
            case 4:
                System.out.println("Jueves");
                break;
            case 5:
                System.out.println("Viernes");
                break;
            case 6:
                System.out.println("Sabado");
                break;
            case 7:
                System.out.println("Domingo");
                break;
            default:
                System.out.println("Has introducido un valor fuera del válido...");
        }

    }
}
