/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.eje5_loops;

public class App {

    public static void main(String[] args) {

        int i = 1;
        
        while (i <= 20) {

            System.out.print(i + ", ");
            i++;
            
        }
    }
}
