/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.eje3_condition;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        int pagoOrdinario = 15, pagoExtraordinario = 20, horas, dinero = 0;
        Scanner myScanner = new Scanner(System.in);

        System.out.println("Introduce las horas semanales trabajadas: ");
        horas = myScanner.nextShort();

        if (horas <= 40 && horas >= 0) {
            dinero = pagoOrdinario * horas;
            System.out.print("Te corresponden " + dinero + "€");
        } else if (horas > 40) {
            dinero = (40 * pagoOrdinario) + ((horas - 40) * pagoExtraordinario);
            System.out.print("Te corresponden " + dinero + "€");
        } else {
            System.out.println("No puedes trabajar horas negativas...");
        }

    }
}
