/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.eje7_loops;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        String pass = "0000", passInput;
        int menu;
        boolean exit;
        Scanner myScanner = new Scanner(System.in);

        do {
            System.out.println("Seleccione una opción (0 - 2):");
            System.out.println("\n\t1. Asignar nueva combinación");
            System.out.println("\t2. Abrir caja fuerte");
            System.out.println("\n\t0. Salir\n\t");
            menu = myScanner.nextInt();
            myScanner.nextLine();

            switch (menu) {
                case 1:

                    System.out.println("Introduzca la contraseña anterior (4 caracteres): ");
                    passInput = myScanner.nextLine();

                    if (pass.equals(passInput)) {
                        System.out.println("Contraseña correcta.");
                        do {
                            System.out.println("Introduzca una nueva contraseña (4 caracteres): ");
                            passInput = myScanner.nextLine();
                            if (passInput.length() == 4) {
                                pass = passInput;
                            } else {
                                System.out.println("Debe ser de 4 caracteres!!");
                            }
                        } while (passInput.length() != 4);
                    } else {
                        System.out.println("ERROR: Contraseña incorrecta...");
                    }

                    exit = false;
                    break;
                case 2:
                    System.out.println("Introduce la contraseña (4 caracteres): ");
                    passInput = myScanner.nextLine();
                    myScanner.reset();
                    if (pass.equals(passInput)) {

                        System.out.println("Caja fuerte abierta!");

                    } else {

                        System.out.println("ERROR: Contraseña incorrecta...");

                    }
                    exit = false;
                    break;
                case 0:

                    exit = true;
                    break;
                default:
                    System.out.println("Por favor, introduzca una opción válida...");
                    exit = false;
            }
        } while (!exit);
    }
}
