/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.eje3_loops;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        for (int i = 1; i <= 20; i++) {

            System.out.print(i + ", ");

        }
    }
}