/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.eje1_IO;

public class App {

    public static void main(String[] args) {

        int x = 200, y = 111, suma, resta, multiplicacion;
        float division;

        suma = x + y;
        resta = x - y;
        multiplicacion = x * y;
        division =  Float.intBitsToFloat(x) / Float.intBitsToFloat(y);

        System.out.println("X = " + x + "\nY = " + y + "\nSuma = " + suma + "\nResta = " + resta + "\nMultiplicación = " + multiplicacion + "\nDivisión = " + division + "\n");

    }
}
