/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalga.eje1_conditions;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        int hora;
        Scanner myScanner = new Scanner(System.in);

        System.out.println("Escriba una hora (1 - 24): ");
        hora = myScanner.nextInt();

        if (hora >= 6 && hora <= 12) {
            
            System.out.println("Buenos dias");
            
        } else if (hora >= 13 && hora <= 20) {
            
            System.out.println("Buenas tardes");
            
        } else if (hora >= 21 && hora <= 24 || hora >= 1 && hora <= 5) {
            
            System.out.println("Buenas noches");
            
        } else {
            
            System.out.println("Has introducido una hora invalida");           
            
        }
    }
}
