/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.eje6_loops;

public class App {

    public static void main(String[] args) {

        int i = 1;
        
        do {

            System.out.print(i + ", ");
            i++;
            
        } while (i <= 20);
    }
}