/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.eje3_IO;


public class App {

    public static void main(String[] args) {

        String nombre = "Adrián Borio Muñoz";

        System.out.println(nombre);

    }
}
