/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.eje1_loops;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        int numero;
        Scanner myScanner = new Scanner(System.in);

        System.out.println("Introduce un número: ");
        numero = myScanner.nextInt();

        for (int i = 1; i <= 10; i++) {
            
            System.out.println(numero * i);
            
        }
    }
}
