/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.eje6_IO;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        float valor1, valor2, valor3, suma, total, IVA = 21.0f;
        Scanner myScanner = new Scanner(System.in);

        System.out.println("Introduce el primer valor: ");
        valor1 = myScanner.nextFloat();
        System.out.println("Introduce el segundo valor: ");
        valor2 = myScanner.nextFloat();
        System.out.println("Introduce el tercero valor: ");
        valor3 = myScanner.nextFloat();

        suma = valor1 + valor2 + valor3;
        total = (suma / 100) * (100 - IVA);

        System.out.println("El total es de: " + total);

    }
}
