/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.eje4_IO;

public class App {

    public static void main(String[] args) {

        String nombre = "Adrián Borio Muñoz", direccion = "Avenida Manuel Gorría, 75-1A", telefono = "620958390";

        System.out.println("Mi nombre es: " + nombre
                + "\nMi dirección es: " + direccion
                + "\nMi teléfono es: " + telefono);

    }
}
